codecov:
  max_report_age: off

coverage:
  ignore:
    - "tests/.*"
    - "pnab/driver/jupyter_widgets.py"
    - "pnab/extras.py"
    - "pnab/__init__.py"
  status:
    project:
      default:
        threshold: 50%
    patch:
      default:
        threshold: 50%
