codecov:
  max_report_age: off
  notify:
    after_n_builds: 1
    require_ci_to_pass: no    

coverage:
  ignore:
    - "tests/.*"
  status:
    project:
      default:
        threshold: 50%
    patch:
      default:
        threshold: 50%
