extraction:
  python:
    python_setup:
      version: 3
  cpp:
    configure:
      command:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda config --set ssl_verify no
        - conda update -q conda
        - PYTHON_VER='3.8'
        - conda create -n pnab -c conda-forge python=$PYTHON_VER cmake gcc_linux-64 gxx_linux-64 openbabel eigen pybind11
        - source activate pnab
        - cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE="$CONDA_PREFIX/bin/python" -DOPENBABEL_DIR="$CONDA_PREFIX"
    index:
      build_command:
        - cd build
        - make
