    
language: python
sudo: false
matrix:
  include:

  - env:
    - PYTHON_VER='3.6'

  - env:
    - PYTHON_VER='3.7'

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda info -a

  - conda create -n pNAB python=$PYTHON_VER numpy cmake openbabel eigen pybind11 py3dmol pytest pytest-cov codecov -c openbabel -c conda-forge
  - source activate pNAB
  - conda list

before_script:
  - python -V

script:
  - pwd
  - python setup.py install
  - cd build
  - pytest --cov

notifications:
  email: false

after_success:
  - codecov --token="aeae5652-faed-4a41-986d-69006b8a3a6b"
