    
language: python
sudo: false
matrix:
  include:

  #- env:
  #  - PYTHON_VER='3.6'

  - env:
    - PYTHON_VER='3.7'

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda info -a

  - conda create -q -n tenv python=$PYTHON_VER numpy
  - source activate tenv
  - conda install -c anaconda cmake
  - conda install -c openbabel openbabel
  - conda install -c conda-forge eigen
  - conda install -c conda-forge pybind11
  - conda install pytest pytest-cov codecov -c conda-forge
  - pip install py3DMol
  - conda list

before_script:
  - python -V

script:
  - pwd
  - python setup.py install
  - cd
  - python -c "import sys, pNAB; rc = pNAB.test(extras=['--cov']); sys.exit(rc)"

notifications:
  email: false

after_success:
  - codecov
