KEEPCFLAGS=$CFLAGS
KEEPFCFLAGS=$FCFLAGS
KEEPCXXFLAGS=$CXXFLAGS
KEEPLDFLAGS=$LDFLAGS
unset CFLAGS
unset FCFLAGS
unset CXXFLAGS
unset LDFLAGS
$PYTHON setup.py install
export CFLAGS=KEEPCFLAGS
export FCFLAGS=KEEPFCFLAGS
export CXXFLAGS=KEEPCXXFLAGS
export LDFLAGS=KEEPLDFLAGS
