target_platform:
    - osx-64                           # [osx]
    - linux-64                         # [linux]
    - win-64                           # [win]
CONDA_BUILD_SYSROOT:
    - /Users/github/SDKs/MacOSX10.9.sdk  # [osx]
cxx_compiler:
    - gxx                              # [linux]
    - clangxx                          # [osx]
python:
    - 3.11
    - 3.10
PY_ABBR:
    - python3.11m
    - python3.10m

zip_keys:
    - python
    - PY_ABBR
