target_platform:
    - osx-64                           # [osx]
    - linux-64                         # [linux]
    - win-64                           # [win]
CONDA_BUILD_SYSROOT:
    - /Users/github/SDKs/MacOSX10.9.sdk  # [osx]
cxx_compiler:
    - gxx                              # [linux]
    - clangxx                          # [osx]
cxx_compiler_version:
    - 7.3.0                            # [linux]
    - 8.0.0                            # [osx]

openbabel:
    - 3.0.0
pybind11:
    - 2.4.3
ipywidgets:
    - 7.5.1
python:
    - 3.8
    - 3.7
PY_ABBR:
    - python3.8m
    - python3.7m

zip_keys:
    - python
    - PY_ABBR
