package:
  name: pnab
  version: "0.1.0"

source:
  #path: ../../../pNAB
  git_url: git@github.com:alenaizan/pNAB.git  # [linux]
  git_url: https://github.com/alenaizan/pNAB.git  # [osx]
  git_tag: labdriver

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - eigen
    - openbabel {{ openbabel }}
    - pybind11
    - python {{ python }}
  run:
    - numpy
    - {{ pin_compatible('openbabel', max_pin='x.x') }}
    - {{ pin_compatible('python', max_pin='x.x') }}
    - py3dmol

test:
  imports:
    - pNAB
  requires:
    - pytest
  commands:
    - pytest --pyargs pNAB

about:
  home: https://github.com/alenaizan/pNAB
  license: None
  license_family: None
  summary: Nucleic Acid Builder
