package:
  name: pnab
  version: "1.0.0"

source:
  git_url: https://github.com/alenaizan/pnab.git
  git_tag: v1.0.0

build:
  number: 0

requirements:
  build:
    - git
    - {{ compiler('cxx') }}
    - cmake
  host:
    - eigen
    - openbabel {{ openbabel }}
    - pybind11 {{ pybind11 }}
    - python {{ python }}
    - ipywidgets {{ ipywidgets }}
  run:
    - numpy
    - {{ pin_compatible('openbabel', max_pin='x.x') }}
    - {{ pin_compatible('python', max_pin='x.x') }}
    - {{ pin_compatible('ipywidgets', min_pin='x.x', max_pin='x.x') }}
    - nglview
    - pyyaml

test:
  imports:
    - pnab
  requires:
    - pytest
  commands:
    - call set BABEL_DATADIR=%PREFIX%\share\openbabel # [win]
    - python -c "import pnab; pnab.test()"

about:
  home: https://github.com/alenaizan/pnab
  license: GPL
  license_family: GPL
  summary: proto-Nucleic Acid Builder
