package:
  name: pnab
  version: "1.1.3"

source:
  git_url: https://github.com/alenaizan/pnab.git
  git_tag: v1.1.3

build:
  number: 0

requirements:
  build:
    - git
    - {{ compiler('cxx') }}
    - cmake
  host:
    - eigen
    - python
    - openbabel
    - pybind11
  run:
    - python {{ python }}
    - numpy
    - openbabel >=3
    - ipywidgets >=7.5, <8
    - nglview >=2.7
    - pyyaml

test:
  imports:
    - pnab
  requires:
    - pytest
  commands:
    - call set BABEL_DATADIR=%PREFIX%\share\openbabel # [win]
    - python -c "import pnab; pnab.test()"

about:
  home: https://github.com/alenaizan/pnab
  license: GPL
  license_family: GPL
  summary: proto-Nucleic Acid Builder
