package:
  name: pnab
  version: "0.7"

source:
  #path: ../
  git_url: https://github.com/alenaizan/pnab.git  # [linux]
  git_url: https://github.com/alenaizan/pnab.git  # [osx]
  git_tag: v0.7

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
  host:
    - eigen
    - openbabel {{ openbabel }}
    - pybind11
    - python {{ python }}
    - ipywidgets {{ ipywidgets }}
  run:
    - numpy
    - {{ pin_compatible('openbabel', max_pin='x.x') }}
    - {{ pin_compatible('python', max_pin='x.x') }}
    - {{ pin_compatible('ipywidgets', min_pin='x.x', max_pin='x.x') }}
    - nglview
    - pyyaml

test:
  imports:
    - pnab
  requires:
    - pytest
  commands:
    - python -c "import pnab; pnab.test()"

about:
  home: https://github.com/alenaizan/pnab
  license: None
  license_family: None
  summary: proto-Nucleic Acid Builder
