package:
  name: pnab
  version: "0.4.0"

source:
  #path: ../../../pNAB
  git_url: https://github.com/alenaizan/pnab.git  # [linux]
  git_url: https://github.com/alenaizan/pnab.git  # [osx]
  git_tag: v0.4

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - eigen
    - openbabel {{ openbabel }}
    - pybind11
    - python {{ python }}
  run:
    - numpy
    - {{ pin_compatible('openbabel', max_pin='x.x') }}
    - {{ pin_compatible('python', max_pin='x.x') }}
    - ipywidgets
    - py3dmol
    - pyyaml

test:
  imports:
    - pnab
  requires:
    - pytest
  commands:
    - python -c "import pnab; pnab.test()"

about:
  home: https://github.com/alenaizan/pnab
  license: None
  license_family: None
  summary: proto-Nucleic Acid Builder
